<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Learn while playing</title>
    <meta name="description" content="Rédaction de plusieurs cours sur les langages informatique. (Html5 ; CSS3 ; JAVASCRIPT; JQUERY ; PHP ; MYSQL)">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- CSS Bootstrap 3 -->
    <link rel="stylesheet" href="../../Public/Views/vendor/bootstrap/css/bootstrap.min.css">
    <!-- Font-Awesome CDN -->
    <link href="https://opensource.keycdn.com/fontawesome/4.7.0/font-awesome.min.css" rel="stylesheet" />
    <!-- CSS Perso -->
    <link rel="stylesheet" href="../../Public/Views/vendor/css/myStyle.css">
    <!-- Fonts-google.com -->
    <link href="https://fonts.googleapis.com/css?family=Cinzel+Decorative|Trirong" rel="stylesheet">
</head>
<body>
<!--[if lt IE 7]>
<p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
<![endif]-->
    <?php include "inc/nav.php"; ?>
    <div class="container-fluid" id="myMain">
        <main>
            <?php include "../../App/Controllers/" . $template . ".phtml";?>
        </main>
    </div>

    <footer>
        <?php include "inc/footer.php"; ?>
    </footer>
    <!-- JQuery -->
    <script type="text/javascript" src="../../Public/Views/vendor/js/jquery-3.2.0.min.js"></script>
    <!-- Script Bootstrap 3 -->
    <script type="text/javascript" src="../../Public/Views/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!-- Script perso -->
    <script type="text/javascript" src="../../Public/Views/vendor/js/myScript.js"></script>
</body>
</html>