<ol class="breadcrumb text-center">
    <li>Home</li>
    <li class="active">Vous êtes là !</li>
</ol>

<div class="jumbotron">
    <h2 class="text-center">Le changement c'est maintenant !</h2>
    <hr>
    <p class="lead text-center"><strong>Vous ne pouvez pas avoir échapé à ce préstigieux titre qui n'avait plus aucun sens à nos yeux...</strong></p>
    <p class="text-center"><small>Au jour d'aujourd'hui grâce à l'évolution du numérique, cette phrase prends tout son sens. Elle est bien plus crédible maintenant que dans la bouche d'un quelconque chef de l'État !</small></p>
</div>

<section>
    <div class="row">
        <div class="col-sm-6">
            <article class="well">
                <div class="thumbnail">
                    <img src="../../Public/Views/assets/background/images/abstract/low-poly01.jpg" alt="...">
                    <div class="caption">
                        <h3>I° - Pourquoi ce site ?</h3>
                        <hr>
                        <p>Si ce site prends forme, c'est surtout grâce à ma motivation personnel. Vous serez d'accord avec moi qu'apprendre quelque chose qu'on n'apprécie pas, ne fera que renforcer le dégout qu'on à pour ce métier.
                            Parfois on a pas le choix... Et si c'est votre cas courage mais surtout ne brûler pas les étapes.
                            Pour ma part les langages du web sont une chose que j'ai toujours aimé et ceci depuis 2002.. A cette époque, j'ai passé une formation pour être
                            "technicien de maintenance informatique micro et réseaux".
                            Chose acquise, avec tout de même un immense regret... En effet, nous avons découvert le milieu du web, pendant une semaine où nous concevions des sites personnel en HTML 2... Ce n'était pas jolie jolie mais j'adorais faire ça.
                            La première chose que je me suis dit... "mon plus grand regret" : Il n'y a pas d'avenir dans ce milieu là... Quelles erreurs monumental.. Ou serais-je au jour d'aujourd'hui !?<br /><br />
                            Bref il ne faut pas pensé négativement mais plutôt l'inverse soit, être positif c'est la clé du succès. Aujourd'hui c'est le moment d'apprendre tout ça et cette fois-ci avec une motivation débordante.
                            Alors ce site vous proposera des rappels sur des fondamentaux trouvez par-ci, par-là. Également, je vais vous permettre d'apprendre ce que j'ai moi même appris sur différents MOOC et
                            surtout via ma formation intensive à la 3WA sur Lyon.</p>
                    </div>
                </div>
            </article>
        </div>

        <div class="col-sm-6">
            <article class="well">
                <div class="thumbnail">
                    <img src="../../Public/Views/assets/background/images/abstract/low-poly03.jpg" alt="...">
                    <div class="caption">
                        <h3>II° - Important !!</h3>
                        <hr>
                        <p>Je vous propose de prendre connaissance de quelques points qui sont primordial.</p>
                        <ul>
                            <li>A° - Ne faîtes du copiez collez que quand le code que vous récupérez est pratiquement acquis.</li>
                            <li>B° - N'apprenez jamais un langage par coeur. En effet ces derniers évoluent constamment. Les apprendres seraient une très grosse erreur. (Sachez tout de même que cette erreur est très connu)</li>
                            <li>C° - Renseignez-vous régulièrement sur l'évolution de votre code.</li>
                            <li>D° - Commentez votre code au maximum, vous serez à un moment donné bloqué et ainsi vous allez avoir des soucis au niveau du code.. Quand vous allez demander de l'aide, si votre code est commenté correctement, vous serez plus rapidement aidez... Attention tout de même de ne pas commenter inutilement... </li>
                            <li>E° - Avoir de l'humilité, c'est un très gros point fort. Si vous avez l'impression d'être meilleur qu'un autre, gardez votre fierté de côté, ... (désolé pour le terme qui va suivre) ... dans ce domaine, il n'est aucunement question de savoir qui à la plus grosse, il y a tellement à apprendre que vous ne pourrez jamais tout savoir.</li>
                        </ul>
                    </div>
                </div>
            </article>
        </div>
    </div>
</section>