<ul>
    <li><a href="index.php">Home</a></li>
    <li><a href="shell.php">Shell</a></li>
    <li><a href="github.php">Github</a></li>
    <li><a href="markdown.php">Markdown</a></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
</ul>

<hr>

<h2>Découvrez plusieurs mémento pour le web.</h2>