<div class="container-fluid">
    <div class="jumbotron">
        <img src="../../Public/Views/assets/icones/markdown.png" alt="Image du Markdown" id="logo">
        <h2 class="text-center">Markdown</h2>
        <h2 class="text-center"><small>Découverte du Markdown</small></h2>
    </div>

    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
            <li data-target="#myCarousel" data-slide-to="3"></li>
            <li data-target="#myCarousel" data-slide-to="4"></li>
            <li data-target="#myCarousel" data-slide-to="5"></li>
            <li data-target="#myCarousel" data-slide-to="6"></li>
            <li data-target="#myCarousel" data-slide-to="7"></li>
            <li data-target="#myCarousel" data-slide-to="8"></li>
            <li data-target="#myCarousel" data-slide-to="9"></li>
            <li data-target="#myCarousel" data-slide-to="10"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            <!-- Slide 0 -->
            <div class="item active">
                <img src="../../Public/Views/assets/wallpapers/wall2.jpg" alt="...">
                <div class="carousel-caption">
                    teste
                </div>
            </div>

            <!-- Slide 1 -->
            <div class="item">
                <img src="../../Public/Views/assets/wallpapers/wall2.jpg" alt="...">
                <div class="carousel-caption">
                    teste2
                </div>
            </div>

            <!-- Slide 1 -->
            <div class="item">
                <img src="../../Public/Views/assets/wallpapers/wall2.jpg" alt="...">
                <div class="carousel-caption">
                    teste2
                </div>
            </div>

            <!-- Slide 2 -->
            <div class="item">
                <img src="../../Public/Views/assets/wallpapers/wall2.jpg" alt="...">
                <div class="carousel-caption">
                    teste3
                </div>
            </div>

            <!-- Slide 3 -->
            <div class="item">
                <img src="../../Public/Views/assets/wallpapers/wall2.jpg" alt="...">
                <div class="carousel-caption">
                    teste4
                </div>
            </div>

            <!-- Slide 4 -->
            <div class="item">
                <img src="../../Public/Views/assets/wallpapers/wall2.jpg" alt="...">
                <div class="carousel-caption">
                    teste5
                </div>
            </div>

            <!-- Slide 5 -->
            <div class="item">
                <img src="../../Public/Views/assets/wallpapers/wall2.jpg" alt="...">
                <div class="carousel-caption">
                    teste6
                </div>
            </div>

            <!-- Slide 6 -->
            <div class="item">
                <img src="../../Public/Views/assets/wallpapers/wall2.jpg" alt="...">
                <div class="carousel-caption">
                    teste7
                </div>
            </div>

            <!-- Slide 7 -->
            <div class="item">
                <img src="../../Public/Views/assets/wallpapers/wall2.jpg" alt="...">
                <div class="carousel-caption">
                    teste8
                </div>
            </div>

            <!-- Slide 8 -->
            <div class="item">
                <img src="../../Public/Views/assets/wallpapers/wall2.jpg" alt="...">
                <div class="carousel-caption">
                    teste9
                </div>
            </div>

            <!-- Slide 9 -->
            <div class="item">
                <img src="../../Public/Views/assets/wallpapers/wall2.jpg" alt="...">
                <div class="carousel-caption">
                    teste10
                </div>
            </div>

        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

</div>